### ISSUE TITLE
Crash Report 1.3.0

### ISSUE THREAD

**Issue by idonhavename** [EpicSquid/Blockcraftery#52]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  CTMCorePlugin (CTM-MC1.12.2-0.3.3.22 (1).jar)
  ShutdownPatcher (mcef-1.12.2-0.9-coremod.jar)
Contact their authors BEFORE contacting forge

// Don't do that.

Time: 6/20/19 12:26 AM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderException: blockcraftery Failed load class: epicsquid.blockcraftery.Blockcraftery
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:544)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:593)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: epicsquid.blockcraftery.Blockcraftery
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.minecraftforge.fml.common.ModClassLoader.loadClass(ModClassLoader.java:75)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:539)
	... 36 more
Caused by: java.io.FileNotFoundException: C:\Users\USER\Documents\Curse\Minecraft\Instances\Too Easy (The system cannot find the file specified)
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:220)
	at java.util.zip.ZipFile.<init>(ZipFile.java:150)
	at java.util.jar.JarFile.<init>(JarFile.java:166)
	at java.util.jar.JarFile.<init>(JarFile.java:103)
	at sun.net.www.protocol.jar.URLJarFile.<init>(URLJarFile.java:93)
	at sun.net.www.protocol.jar.URLJarFile.getJarFile(URLJarFile.java:69)
	at sun.net.www.protocol.jar.JarFileFactory.get(JarFileFactory.java:94)
	at sun.net.www.protocol.jar.JarURLConnection.connect(JarURLConnection.java:122)
	at sun.net.www.protocol.jar.JarURLConnection.getJarFile(JarURLConnection.java:89)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:145)
	... 42 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 330924976 bytes (315 MB) / 671088640 bytes (640 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2838 39 mods loaded, 39 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                      | Version           | Source                                          | Signature                                |
	|:----- |:----------------------- |:----------------- |:----------------------------------------------- |:---------------------------------------- |
	| LC    | minecraft               | 1.12.2            | minecraft.jar                                   | None                                     |
	| LC    | mcp                     | 9.42              | minecraft.jar                                   | None                                     |
	| LC    | FML                     | 8.0.99.99         | forge-1.12.2-14.23.5.2838.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LC    | forge                   | 14.23.5.2838      | forge-1.12.2-14.23.5.2838.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LE    | blockcraftery           | 1.12.2-1.3.0      | blockcraftery-1.12.2-1.3.0.jar                  | None                                     |
	| L     | ctm                     | MC1.12.2-0.3.3.22 | CTM-MC1.12.2-0.3.3.22 (1).jar                   | None                                     |
	| L     | chisel                  | MC1.12.2-0.2.1.35 | Chisel-MC1.12.2-0.2.1.35.jar                    | None                                     |
	| L     | codechickenlib          | 3.2.2.353         | CodeChickenLib-1.12.2.jar                       | None                                     |
	| L     | redstoneflux            | 2.1.0             | RedstoneFlux-1.12-2.1.0.6-universal.jar         | None                                     |
	| L     | cofhcore                | 4.6.3             | CoFHCore-1.12.2-4.6.3.27-universal.jar          | None                                     |
	| L     | cofhworld               | 1.3.1             | CoFHWorld-1.12.2-1.3.1.7-universal.jar          | None                                     |
	| L     | valkyrielib             | 1.12.2-2.0.20.1   | valkyrielib-1.12.2-2.0.20.1.jar                 | None                                     |
	| L     | environmentaltech       | 1.12.2-2.0.20.1   | environmentaltech-1.12.2-2.0.20.1.jar           | None                                     |
	| L     | etlunar                 | 1.12.2-2.0.20.1   | etlunar-1.12.2-2.0.20.1.jar                     | None                                     |
	| L     | extrautils2             | 1.0               | extrautils2-1.12-1.9.9 (1).jar                  | None                                     |
	| L     | flansmod                | 5.5.2             | Flan's Mod-1.12.2-5.5.2.jar                     | None                                     |
	| L     | flansmodapocalypse      | 1.0               | Flan's Mod-1.12.2-5.5.2.jar                     | None                                     |
	| L     | sonarcore               | 5.0.19            | sonarcore-1.12.2-5.0.19-20 (1).jar              | None                                     |
	| L     | fluxnetworks            | 3.0.19            | fluxnetworks-1.12.2-3.0.19-21.jar               | None                                     |
	| L     | foodexpansion           | 1.3               | FoodExpansion1.3.3-1.12.2.jar                   | None                                     |
	| L     | forgemultipartcbe       | 2.6.1.81          | ForgeMultipart-1.12.2-2.6.1.81-universal.jar    | None                                     |
	| L     | microblockcbe           | 2.6.1.81          | ForgeMultipart-1.12.2-2.6.1.81-universal.jar    | None                                     |
	| L     | minecraftmultipartcbe   | 2.6.1.81          | ForgeMultipart-1.12.2-2.6.1.81-universal.jar    | None                                     |
	| L     | journeymap              | 1.12.2-5.5.3      | journeymap-1.12.2-5.5.3.jar                     | None                                     |
	| L     | mcjtylib_ng             | 3.5.3             | mcjtylib-1.12-3.5.3.jar                         | None                                     |
	| L     | mrtjpcore               | 2.1.3.35          | MrTJPCore-1.12.2-2.1.3.35-universal.jar         | None                                     |
	| L     | notenoughwands          | 1.8.1             | notenoughwands-1.12-1.8.1.jar                   | None                                     |
	| L     | projectred-core         | 4.9.1.92          | ProjectRed-1.12.2-4.9.1.92-Base.jar             | None                                     |
	| L     | projectred-illumination | 4.9.1.92          | ProjectRed-1.12.2-4.9.1.92-lighting.jar         | None                                     |
	| L     | reborncore              | 3.13.12.447       | RebornCore-1.12.2-3.13.12.447-universal.jar     | None                                     |
	| L     | refinedstorage          | 1.6.14            | refinedstorage-1.6.14.jar                       | None                                     |
	| L     | rebornstorage           | 1.0.0             | RebornStorage-1.12.2-3.3.4.85.jar               | None                                     |
	| L     | refinedstorageaddons    | 0.4.4             | refinedstorageaddons-0.4.4.jar                  | None                                     |
	| L     | rftools                 | 7.71              | rftools-1.12-7.71.jar                           | None                                     |
	| L     | thermalfoundation       | 2.6.3             | ThermalFoundation-1.12.2-2.6.3.27-universal.jar | None                                     |
	| L     | thermalexpansion        | 5.5.4             | ThermalExpansion-1.12.2-5.5.4.43-universal.jar  | None                                     |
	| L     | thermaldynamics         | 2.5.5             | ThermalDynamics-1.12.2-2.5.5.21-universal.jar   | None                                     |
	| L     | universalmodifiers      | 1.12.2-1.0.16.1   | valkyrielib-1.12.2-2.0.20.1.jar                 | None                                     |
	| L     | mysticallib             | 1.12.2-1.2.1      | mysticallib-1.12.2-1.2.1.jar                    | None                                     |

	Loaded coremods (and transformers): 
CTMCorePlugin (CTM-MC1.12.2-0.3.3.22 (1).jar)
  team.chisel.ctm.client.asm.CTMTransformer
ShutdownPatcher (mcef-1.12.2-0.9-coremod.jar)
  net.montoyo.mcef.coremod.ShutdownPatcher
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.4.0 NVIDIA 344.24' Renderer: 'GeForce 830M/PCIe/SSE2'

**Comment by EpicSquid** [comment]
"FileNotFoundException: C:\Users\USER\Documents\Curse\Minecraft\Instances\Too Easy" thats your issue. Either you have a corrupt instance or a corrupt jar in it.
